### ISSUE TITLE
android emoji pls?

### ISSUE THREAD

**Issue by DeleteThisAcount** [GreenBayRules/ScratchMoji#2]
https://cdn0.vox-cdn.com/uploads/chorus_asset/file/6345529/old.0.jpg
https://cdn.pastemagazine.com/www/articles/new%20android%20emoji%20main.jpg

**Comment by Sheshank-s** [comment]
hmm... sure ill add it to custom

**Comment by Sheshank-s** [comment]
Actually, I don't think this will be added...

**Comment by DeleteThisAcount** [comment]
Nooô
